update from upstream http://wiki.debian.org/initramfs-tools

diff --git a/usr/sbin/mkinitramfs b/usr/sbin/mkinitramfs
--- a/usr/sbin/mkinitramfs
+++ b/usr/sbin/mkinitramfs
@@ -7,19 +7,25 @@ export PATH='/usr/bin:/sbin:/bin'
 keep="n"
 CONFDIR="/etc/initramfs-tools"
 verbose="n"
-errors_to="2>/dev/null"
-BUSYBOXDIR="/usr/lib/initramfs-tools/bin/"
-# BUSYBOXDIR="/bin"
 
-OPTIONS=`getopt -o d:ko:r:v --long supported-host-version:,supported-target-version: -n "$0" -- "$@"`
+test -e /bin/busybox && BUSYBOXDIR=/bin
+test -e /usr/lib/initramfs-tools/bin/busybox && BUSYBOXDIR=/usr/lib/initramfs-tools/bin
+export BUSYBOXDIR
+
+OPTIONS=`getopt -o c:d:ko:r:v -n "$0" -- "$@"`
 
 # Check for non-GNU getopt
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [ $? != 0 ] ; then echo "W: non-GNU getopt" >&2 ; exit 1 ; fi
 
 eval set -- "$OPTIONS"
 
 while true; do
 	case "$1" in
+       -c)
+                compress="$2"
+                shift 2
+                ;;
+
 	-d)
 		CONFDIR="$2"
 		shift 2
@@ -44,14 +50,6 @@ while true; do
 		verbose="y"
 		shift
 		;;
-	--supported-host-version)
-		supported_host_version="$2"
-		shift 2
-		;;
-	--supported-target-version)
-		supported_target_version="$2"
-		shift 2
-		;;
 	--)
 		shift
 		break
@@ -63,23 +61,6 @@ while true; do
 	esac
 done
 
-# FIXME: remove after Lenny (needed for Etch linux-images)
-if [ -n "$supported_host_version" ] || [ -n "$supported_target_version" ]; then
-	if [ -n "$supported_host_version" ]; then
-		host_upstream_version="${supported_host_version%%-*}"
-	fi
-	if [ -n "$supported_target_version" ]; then
-		target_upstream_version="${supported_target_version%%-*}"
-		ypkg --compare-version "$target_upstream_version" "2.6.12" 2>/dev/null
-		#"$target_upstream_version" less than "2.6.12"
-		if [ $? -eq 2 ]; then
-			exit 2
-		fi
-	fi
-	echo "Depreciation warning: use ramdisk=mkinitramfs-kpkg."
-	exit 0
-fi
-
 # For dependency ordered mkinitramfs hook scripts.
 . /usr/share/initramfs-tools/scripts/functions
 . /usr/share/initramfs-tools/hook-functions
@@ -87,11 +68,12 @@ fi
 . "${CONFDIR}/initramfs.conf"
 EXTRA_CONF=''
 for i in /usr/share/initramfs-tools/conf.d/* ${CONFDIR}/conf.d/*; do
-	EXTRA_CONF="${EXTRA_CONF} $(basename $i \
-		| grep '^[[:alnum:]][[:alnum:]\._-]*$' | grep -v '\.pkg-.*$')";
+       [ -e $i ] && EXTRA_CONF="${EXTRA_CONF} $(basename $i \
+               | grep '^[[:alnum:]][[:alnum:]\._-]*$' | grep -v '\.dpkg-.*$')";
+
 done
 # FIXME: deprecated those settings on mkinitramfs run
-#        these conf dirs are for boot scripts and land on initramfs
+#       these conf dirs are for boot scripts and land on initramfs
 for i in ${EXTRA_CONF}; do
 	if [ -e  ${CONFDIR}/conf.d/${i} ]; then
 		. ${CONFDIR}/conf.d/${i}
@@ -107,7 +89,7 @@ for i in /usr/share/initramfs-tools/conf-hooks.d/*; do
 	fi
 done
 
-if [ -n "${UMASK}" ]; then
+if [ -n "${UMASK:-}" ]; then
 	umask "${UMASK}"
 fi
 
@@ -148,24 +130,53 @@ case "${version}" in
 	;;
 esac
 
+# Check userspace and kernel support for compressed initramfs images
+if [ -z "${compress:-}" ]; then
+       compress=${COMPRESS}
+else
+       COMPRESS=${compress}
+fi
+
+if ! command -v "${compress}" >/dev/null 2>&1; then
+       compress=gzip
+       [ "${verbose}" = y ] && \
+               echo "No ${COMPRESS} in ${PATH}, using gzip"
+       COMPRESS=gzip
+fi
+
+if ! `grep -q -i ^config_rd_${COMPRESS%p} /boot/config-${version}` ; then
+       compress=gzip
+       [ "${verbose}" = y ] && \
+               echo "linux-2.6 misses ${COMPRESS} support, using gzip"
+fi
+
+[ "${compress}" = lzop ] && compress="lzop -9"
+[ "${compress}" = xz ] && compress="xz -8 --check=crc32"
+
 if [ -d "${outfile}" ]; then
-	echo "${outfile} is a directory"
+	echo "${outfile} is a directory" >&2
 	exit 1
 fi
 
 MODULESDIR="/lib/modules/${version}"
 
 if [ ! -e "${MODULESDIR}" ]; then
-	echo "Cannot find ${MODULESDIR}"
-	exit 1
+	echo "WARNING: missing ${MODULESDIR}"
+	echo "Device driver support needs thus be built-in linux image!"
 fi
 if [ ! -e "${MODULESDIR}/modules.dep" ]; then
 	depmod ${version}
 fi
 
-DESTDIR="$(mktemp -t -d mkinitramfs_XXXXXX)" || exit 1
+DESTDIR="$(mktemp -d ${TMPDIR:-/tmp}/mkinitramfs_XXXXXX)" || exit 1
 chmod 755 "${DESTDIR}"
-__TMPCPIOGZ="$(mktemp -t mkinitramfs-OL_XXXXXX)" || exit 1
+# do not execute cache_run_scripts() if mounted with noexec
+NOEXEC=""
+fs=$(df -P $DESTDIR | tail -1 | awk '{print $6}')
+if [ -n "$fs" ] && mount | grep -q "on $fs .*noexec" ; then
+       NOEXEC=1
+fi
+__TMPCPIOGZ="$(mktemp ${TMPDIR:-/tmp}/mkinitramfs-OL_XXXXXX)" || exit 1
 
 PKG_ARCH=$(uname -r)
 
@@ -177,14 +188,14 @@ export CONFDIR
 export DESTDIR
 export PKG_ARCH
 export verbose
-export KEYMAP
 export MODULES
+export BUSYBOX
 export COMPCACHE_SIZE
 
 # Private, used by 'catenate_cpiogz'.
 export __TMPCPIOGZ
 
-for d in bin conf/conf.d etc lib/modules sbin scripts ${MODULESDIR}; do
+for d in bin conf/conf.d etc lib/modules run sbin scripts ${MODULESDIR}; do
 	mkdir -p "${DESTDIR}/${d}"
 done
 
@@ -219,25 +230,20 @@ list)
 	# nothing to add
 	;;
 *)
-	echo "mkinitramfs: Warning unsupported MODULES setting: ${MODULES}."
-	echo "mkinitramfs: Falling back to MODULES=most."
+	echo "W: mkinitramfs: unsupported MODULES setting: ${MODULES}."
+	echo "W: mkinitramfs: Falling back to MODULES=most."
 	auto_add_modules
 	;;
 esac
 
-# Have to do each file, because cpio --dereference doesn't recurse down
-# symlinks.
+# Resolve hidden dependencies
+hidden_dep_add_modules
 
-# klibc
-ln -s /usr/lib/klibc/bin/* ${DESTDIR}/bin
-ln -s /lib/klibc-*.so ${DESTDIR}/lib
-rm -f ${DESTDIR}/bin/kinit* ${DESTDIR}/bin/gzip
-
-copy_exec /usr/share/initramfs-tools/init /init
+cp -p /usr/share/initramfs-tools/init ${DESTDIR}/init
 
 # add existant boot scripts
 for b in $(cd /usr/share/initramfs-tools/scripts/ && find . \
-	-regextype posix-extended -regex '.*/[[:alnum:]_]+$' -type f); do
+	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f); do
 	option=$(sed '/^OPTION=/!d;$d;s/^OPTION=//;s/[[:space:]]*$//' "/usr/share/initramfs-tools/scripts/${b}")
 	[ -z "${option}" ] || eval test -n \"\${$option}\" -a \"\${$option}\" != \"n\" || continue
 
@@ -247,7 +253,7 @@ for b in $(cd /usr/share/initramfs-tools/scripts/ && find . \
 		"${DESTDIR}/scripts/$(dirname "${b}")/"
 done
 for b in $(cd "${CONFDIR}/scripts" && find . \
-	-regextype posix-extended -regex '.*/[[:alnum:]_]+$' -type f); do
+	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f); do
 	option=$(sed '/^OPTION=/!d;$d;s/^OPTION=//;s/[[:space:]]*$//' "${CONFDIR}/scripts/${b}")
 	[ -z "${option}" ] || eval test -n \"\${$option}\" -a \"\${$option}\" != \"n\" || continue
 
@@ -257,7 +263,8 @@ for b in $(cd "${CONFDIR}/scripts" && find . \
 done
 
 echo "PKG_ARCH=${PKG_ARCH}" > ${DESTDIR}/conf/arch.conf
-copy_exec "${CONFDIR}/initramfs.conf" /conf
+cp -p "${CONFDIR}/initramfs.conf" ${DESTDIR}/conf
+
 for i in ${EXTRA_CONF}; do
 	if [ -e "${CONFDIR}/conf.d/${i}" ]; then
 		copy_exec "${CONFDIR}/conf.d/${i}" /conf/conf.d
@@ -267,55 +274,22 @@ for i in ${EXTRA_CONF}; do
 done
 
 # ROOT hardcoding
-if [ -n "${ROOT}" ]; then
+if [ -n "${ROOT:-}" ]; then
 	echo "ROOT=${ROOT}" > ${DESTDIR}/conf/conf.d/root
 fi
 
-# Busybox
-if [ "${BUSYBOX}" = "n" ] || [ ! -e ${BUSYBOXDIR}/busybox ]; then
-	mv ${DESTDIR}/bin/sh.shared ${DESTDIR}/bin/sh
-	# those root need busybox
-	eval "$(mount | awk '/ \/ / {print "r_dev=" $1; exit}')"
-	if [ "${r_dev#/dev/mapper/}" != "${r_dev}" ] \
-		|| [ "${r_dev#/dev/md}" != "${r_dev}" ]; then
-		echo "Warning: Busybox is required for successful boot!"
-	fi
-else
-	# Busybox is configured to prefer its own applets, so remove
-	# duplication from klibc.
-	for cmd in `${BUSYBOXDIR}/busybox | sed -n '/functions:$/,$p' \
-		| tail -n +2 \
-		| sed -e 's/[[:space:]]*//g; s/,$//; s/,/\n/g; /busybox/d'`; do
-		rm -f ${DESTDIR}/bin/${cmd}
-	done
-	rm -f ${DESTDIR}/bin/sh
-	rm -f ${DESTDIR}/bin/busybox
-	copy_exec ${BUSYBOXDIR}/busybox /bin/busybox
-	ln -s ${BUSYBOXDIR}/busybox ${DESTDIR}/bin/sh
-	# klibc's version is just wrong; patch sent upstream by maks
-	rm -f ${DESTDIR}/bin/chroot
-	# klibc's version can't display mounts, which casper needs; fuse
-	# needs /bin/mount to exist, so add a symlink
-	rm -f ${DESTDIR}/bin/mount
-	ln -s busybox ${DESTDIR}/bin/mount
-	# ... but some scripts expect /bin/sleep to exist. Boo.
-	ln -s busybox ${DESTDIR}/bin/sleep
-	# Useless
-	for cmd in minips nuke sh.shared; do
-		rm -f ${DESTDIR}/bin/${cmd}
-	done
+if ! command -v ldd >/dev/null 2>&1 ; then
+       echo "WARNING: no ldd around - install libc-bin" >&2
+       exit 1
 fi
 
 copy_exec /usr/lib/initramfs-tools/bin/wait-for-root /sbin
 
-# Modutils
+# module-init-tools
 copy_exec /sbin/modprobe /sbin
-copy_exec /sbin/depmod /sbin
 copy_exec /sbin/rmmod /sbin
-mkdir -p "/etc/modprobe.d" "${DESTDIR}/etc/modprobe.d"
-if ls /etc/modprobe.d/* >/dev/null 2>/dev/null;then
-	cp -a /etc/modprobe.d/* "${DESTDIR}/etc/modprobe.d/"
-fi
+mkdir -p "${DESTDIR}/etc/modprobe.d"
+cp -a /etc/modprobe.d/* "${DESTDIR}/etc/modprobe.d/"
 
 # util-linux
 copy_exec /sbin/blkid /sbin
@@ -328,15 +302,25 @@ fi
 run_scripts /usr/share/initramfs-tools/hooks optional
 run_scripts "${CONFDIR}"/hooks optional
 
-# cache run order
-for b in $(cd "${DESTDIR}/scripts" && find . \
-	-mindepth 1 -type d); do
-	cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
-done
+# cache boot run order
+if [ -n "$NOEXEC" ]; then
+       echo "W: TMPDIR is mounted noexec, will not cache run scripts."
+else
+       for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
+               cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
+       done
+fi
 
 # generate module deps
 depmod -a -b "${DESTDIR}" ${version}
-rm "${DESTDIR}"/lib/modules/${version}/modules.*map 2>/dev/null
+rm -f "${DESTDIR}/lib/modules/${version}"/modules.*map
+
+# make sure that library search path is up to date
+cp -ar /etc/ld.so.conf* "$DESTDIR"/etc/
+if ! ldconfig -r "$DESTDIR" ; then
+       [ $(id -u) != "0" ] \
+       && echo "ldconfig might need uid=0 (root) for chroot()" >&2
+fi
 
 # Apply DSDT to initramfs
 if [ -e "${CONFDIR}/DSDT.aml" ]; then
@@ -344,7 +328,21 @@ if [ -e "${CONFDIR}/DSDT.aml" ]; then
 fi
 
 # Remove any looping or broken symbolic links, since they break cpio.
-(cd "${DESTDIR}" && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' | xargs -rL1 rm -f)
+[ "${verbose}" = y ] && xargs_verbose="-t"
+(cd "${DESTDIR}" && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' \
+       | xargs ${xargs_verbose:-} -rL1 rm -f)
+
+# dirty hack for armhf's double-linker situation; if we have one of
+# the two known eglibc linkers, nuke both and re-create sanity
+if [ "$DPKG_ARCH" = armhf ]; then
+       if [ -e "${DESTDIR}/lib/arm-linux-gnueabihf/ld-linux.so.3" ] || \
+          [ -e "${DESTDIR}/lib/ld-linux-armhf.so.3" ]; then
+               rm -f "${DESTDIR}/lib/arm-linux-gnueabihf/ld-linux.so.3"
+               rm -f "${DESTDIR}/lib/ld-linux-armhf.so.3"
+               cp -aL /lib/ld-linux-armhf.so.3 "${DESTDIR}/lib/"
+               ln -sf /lib/ld-linux-armhf.so.3 "${DESTDIR}/lib/arm-linux-gnueabihf/ld-linux.so.3"
+       fi
+fi
 
 [ "${verbose}" = y ] && echo "Building cpio ${outfile} initramfs"
 (
@@ -354,19 +352,28 @@ fi
 # cd "${DESTDIR}" && find . | cpio --quiet --dereference -o -H newc | lzma -7 >"${outfile}"
 exec 3>&1
 eval `
-    # http://cfaj.freeshell.org/shell/cus-faq-2.html
-    exec 4>&1 >&3 3>&-
-    cd  "${DESTDIR}" 
-    {
-        find . 4>&-; echo "ec1=$?;" >&4
-    } | {
-        cpio --quiet --dereference -o -H newc 4>&-; echo "ec2=$?;" >&4
-    } | lzma -7 >"${outfile}"
-    echo "ec3=$?;" >&4
+      # http://cfaj.freeshell.org/shell/cus-faq-2.html
+      exec 4>&1 >&3 3>&-
+      cd  "${DESTDIR}"
+      {
+              find . 4>&-; echo "ec1=$?;" >&4
+      } | {
+              cpio --quiet -R 0:0 -o -H newc 4>&-; echo "ec2=$?;" >&4
+      } | ${compress} >"${outfile}"
+      echo "ec3=$?;" >&4
 `
-if [ "$ec1" -ne 0 ]; then exit "$ec1"; fi
-if [ "$ec2" -ne 0 ]; then exit "$ec2"; fi
-if [ "$ec3" -ne 0 ]; then exit "$ec3"; fi
+if [ "$ec1" -ne 0 ]; then
+       echo "E: mkinitramfs failure find $ec1 cpio $ec2 $compress $ec3"
+       exit "$ec1"
+fi
+if [ "$ec2" -ne 0 ]; then
+       echo "E: mkinitramfs failure cpio $ec2 $compress $ec3"
+       exit "$ec2"
+fi
+if [ "$ec3" -ne 0 ]; then
+       echo "E: mkinitramfs failure $compress $ec3"
+       exit "$ec3"
+fi
 ) || exit 1
 
 if [ -s "${__TMPCPIOGZ}" ]; then
diff --git a/usr/sbin/update-initramfs b/usr/sbin/update-initramfs
--- a/usr/sbin/update-initramfs
+++ b/usr/sbin/update-initramfs
@@ -3,12 +3,12 @@
 STATEDIR=/var/lib/initramfs-tools
 BOOTDIR=/boot
 CONF=/etc/initramfs-tools/update-initramfs.conf
-KPKGCONF=/etc/kernel-img.conf
 USETRIGGERS=true
 mode=""
 version=""
 
-mkdir -p ${STATEDIR}
+update_initramfs=yes
+backup_initramfs=no
 
 set -e
 
@@ -16,8 +16,8 @@ set -e
 
 usage()
 {
-	if [ -n "${1}" ]; then
-		printf "${@}\n\n" >&2
+	if [ -n "${1:-}" ]; then
+		printf "${*}\n\n" >&2
 	fi
 	cat >&2 << EOF
 Usage: ${0} [OPTION]...
@@ -39,28 +39,28 @@ EOF
 # chroot check
 chrooted()
 {
-        # borrowed from udev's postinst
-        if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
-                # the devicenumber/inode pair of / is the same as that of
-                # /sbin/init's root, so we're *not* in a chroot and hence
-                # return false.
-                return 1
-        fi
-        return 0
+       # borrowed from udev's postinst
+       if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
+               # the devicenumber/inode pair of / is the same as that of
+               # /sbin/init's root, so we're *not* in a chroot and hence
+               # return false.
+               return 1
+       fi
+return 0
 }
 
 mild_panic()
 {
-	if [ -n "${1}" ]; then
-		printf "${@}\n" >&2
+	if [ -n "${1:-}" ]; then
+		printf "${*}\n" >&2
 	fi
 	exit 0
 }
 
 panic()
 {
-	if [ -n "${1}" ]; then
-		printf "${@}\n" >&2
+	if [ -n "${1:-}" ]; then
+		printf "${*}\n" >&2
 	fi
 	exit 1
 }
@@ -68,7 +68,7 @@ panic()
 verbose()
 {
 	if [ "${verbose}" = 1 ]; then
-		printf "${@}\n"
+		printf "${*}\n"
 	fi
 }
 
@@ -117,6 +117,7 @@ backup_booted_initramfs()
 	fi
 
 	# keep booted initramfs
+	boot_initramfs=
 	uptime_days=$(awk '{printf "%d", $1 / 3600 / 24}' /proc/uptime)
 	if [ -n "$uptime_days" ]; then
 		boot_initramfs=$(find "${initramfs}.bak" -mtime +${uptime_days})
@@ -131,9 +132,9 @@ backup_booted_initramfs()
 }
 
 # nuke generated copy
-remove_initramfs()
+remove_initramfs_bak()
 {
-	[ -z "${initramfs_bak}" ] && return 0
+	[ -z "${initramfs_bak:-}" ] && return 0
 	rm -f "${initramfs_bak}"
 	verbose "Removing ${initramfs_bak}"
 }
@@ -151,13 +152,13 @@ generate_initramfs()
 		set_sha1
 	else
 		mkinitramfs_return="$?"
-		remove_initramfs
+		remove_initramfs_bak
 		rm -f "${initramfs}.new"
 		if [ "$mkinitramfs_return" = "2" ]; then
 			# minversion wasn't met, exit 0
 			exit 0
 		fi
-		echo "update-initramfs: failed for ${initramfs}"
+		echo "update-initramfs: failed for ${initramfs} with $mkinitramfs_return." >&2
 		exit $mkinitramfs_return
 	fi
 }
@@ -167,96 +168,21 @@ run_lilo()
 {
 	# show lilo errors on failure
 	if ! lilo -t  > /dev/null 2>&1 ; then
-		echo "ERROR lilo fails for new ${initramfs}:"
+		echo "ERROR lilo fails for new ${initramfs}:" >&2
 		echo
 		lilo -t
 	fi
 	lilo
 }
 
-# check if lilo is on mbr
-mbr_check()
-{
-	# try to discover grub and be happy
-	# FIXME: check grub2 /boot/grub/grub.cfg
-	[ -r /boot/grub/menu.lst ] \
-		&& groot=$(awk '/^root/{print substr($2, 2, 3); exit}' \
-			/boot/grub/menu.lst)
-	[ -e /boot/grub/device.map ] && [ -n "${groot}" ] \
-		&& dev=$(awk "/${groot}/{ print \$NF}" /boot/grub/device.map)
-	[ -n "${dev}" ] && [ -r ${dev} ] \
-		&& dd if="${dev}" bs=512 skip=0 count=1 2> /dev/null \
-		| grep -q GRUB && return 0
-
-	# check out lilo.conf for validity
-	boot=$(awk -F = '/^boot=/{ print $2}' /etc/lilo.conf)
-	[ -z "${boot}" ] && return 0
-	case ${boot} in
-	/dev/md/*)
-		if [ -r /proc/mdstat ]; then
-			MD=${boot#/dev/md/}
-			boot="/dev/$(awk "/^md${MD}/{print substr(\$5, 1, 3)}" \
-			/proc/mdstat)"
-		fi
-		;;
-	/dev/md*)
-		if [ -r /proc/mdstat ]; then
-			MD=${boot#/dev/}
-			boot="/dev/$(awk "/^${MD}/{print substr(\$5, 1, 3)}" \
-			/proc/mdstat)"
-		fi
-		;;
-	esac
-	[ ! -r "${boot}" ] && return 0
-	dd if="${boot}" bs=512 skip=0 count=1 2> /dev/null | grep -q LILO \
-		&& run_lilo && return 0
-
-	# no idea which bootloader is used
-	echo
-	echo "WARNING: grub and lilo installed."
-	echo "If you use grub as bootloader everything is fine."
-	echo "If you use lilo as bootloader you must run lilo!"
-	echo
-}
-
 # Invoke bootloader
 run_bootloader()
 {
-	# if both lilo and grub around, figure out if lilo needs to be run
-	if [ -x "$(command -v update-grub)" ] || [ -e /boot/grub/menu.lst ] \
-	|| [ -e /boot/grub/grub.cfg ]; then
-		if [ -e /etc/lilo.conf ] && [ -x /sbin/lilo ]; then
-			[ -r "${KPKGCONF}" ] && \
-			do_b=$(awk  '/^do_bootloader/{print $3}' "${KPKGCONF}")
-			if [ "${do_b}" = "yes" ] || [ "${do_b}" = "Yes" ] \
-				|| [ "${do_b}" = "YES" ]; then
-				run_lilo
-				return 0
-			elif [ "${do_b}" = "no" ] || [ "${do_b}" = "No" ] \
-				|| [ "${do_b}" = "NO" ]; then
-				return 0
-			else
-				mbr_check
-				return 0
-			fi
-		fi
-		return 0
-	fi
-	if [ -r /etc/lilo.conf ] && [ -x /sbin/lilo ]; then
-		run_lilo
-		return 0
-	fi
-	if [ -x /sbin/elilo ]; then
-		elilo
-		return 0
-	fi
-	if [ -r /etc/zipl.conf ]; then
-		zipl
-	fi
-	if [ -r /etc/kernel-img.conf ] && grep -q '^postinst_hook[[:space:]]*=[[:space:]]*[^[:space:]]' /etc/kernel-img.conf; then
-		if flash-kernel --supported >/dev/null 2>&1; then
-			flash-kernel
-		fi
+	# invoke policy conformant bootloader hooks
+	if [ -d /etc/initramfs/post-update.d/ ]; then
+		run-parts --arg=${version} --arg=${initramfs} \
+	                     /etc/initramfs/post-update.d/
+	        return 0
 	fi
 }
 
@@ -332,11 +258,12 @@ set_current_version()
 
 set_linked_version()
 {
-	if [ -L /initrd.img -a -e /initrd.img ]; then
+	linktarget=
+	if [ -e /initrd.img ] && [ -L /initrd.img ]; then
 		linktarget="$(basename "$(readlink /initrd.img)")"
 	fi
 
-	if [ -L /boot/initrd.img -a -e /boot/initrd.img ]; then
+	if [ -e /boot/initrd.img ] && [ -L /boot/initrd.img ]; then
 		linktarget="$(basename "$(readlink /boot/initrd.img)")"
 	fi
 
@@ -350,6 +277,10 @@ set_linked_version()
 set_highest_version()
 {
 	get_sorted_versions
+        if [ -z "${version_list}" ]; then
+               version=
+               return
+        fi
 	set -- ${version_list}
 	version=${1}
 }
@@ -383,11 +314,11 @@ update()
 	fi
 
 	if [ -z "${version}" ]; then
-		set_linked_version
+		set_highest_version
 	fi
 
 	if [ -z "${version}" ]; then
-		set_highest_version
+		set_linked_version
 	fi
 
 	if [ -z "${version}" ]; then
@@ -422,12 +353,14 @@ delete()
 
 	set_initramfs
 
-	if [ ! -e "${initramfs}" ]; then
-		panic "Cannot delete ${initramfs}, doesn't exist."
-	fi
-
-	if ! version_exists "${version}"; then
-		panic "Cannot delete version ${version}: Not created by this utility."
+	if [ "${takeover}" = 0 ]; then
+	   if [ ! -e "${initramfs}" ]; then
+	 	 panic "Cannot delete ${initramfs}, doesn't exist."
+	   fi
+	   
+	   if ! version_exists "${version}"; then
+	   	panic "Cannot delete version ${version}: Not created by this utility."
+	   fi
 	fi
 
 	altered_check
@@ -436,7 +369,7 @@ delete()
 
 	delete_sha1
 
-	rm -f "${initramfs}"
+	rm -f "${initramfs}" "${initramfs}.bak"
 }
 
 # Check for update mode on existing and modified initramfs
@@ -487,7 +420,7 @@ while getopts "k:cudyvtb:h?" flag; do
 	b)
 		BOOTDIR="${OPTARG}"
 		if [ ! -d "${BOOTDIR}" ]; then
-			echo "Error: ${BOOTDIR} is not a directory."
+			echo "Error: ${BOOTDIR} is not a directory." >&2
 			exit 1
 		fi
 		;;
@@ -496,6 +429,13 @@ while getopts "k:cudyvtb:h?" flag; do
 		;;
 	esac
 done
+
+shift $((${OPTIND} - 1))
+
+if [ $# -ne 0 ]; then
+       echo "Invalid argument for option -k." >&2
+       usage
+fi
 
 # Validate arguments
 if [ -z "${mode}" ]; then
@@ -522,11 +462,8 @@ if [ "${version}" = "all" ] \
 		OPTS="${OPTS} -y"
 	fi
 	for u_version in ${version_list}; do
-		# Don't stop if one version doesn't work.
-		set +e
 		verbose "Execute: ${0} -${mode} -k \"${u_version}\" ${OPTS}"
 		"${0}" -${mode} -k "${u_version}" ${OPTS}
-		set -e
 	done
 	exit 0
 fi
diff --git a/usr/share/initramfs-tools/scripts/functions b/usr/share/initramfs-tools/scripts/functions
--- a/usr/share/initramfs-tools/scripts/functions
+++ b/usr/share/initramfs-tools/scripts/functions
@@ -3,38 +3,32 @@
 _log_msg()
 {
 	if [ "$quiet" = "y" ]; then return; fi
-	echo "$@"
+	printf "$@"
 }
 
 log_success_msg()
 {
-	_log_msg "Success: $@"
+	_log_msg "Success: $@\n"
 }
 
 log_failure_msg()
 {
-	_log_msg "Failure: $@"
+	_log_msg "Failure: $@\n"
 }
 
 log_warning_msg()
 {
-	_log_msg "Warning: $@"
+	_log_msg "Warning: $@\n"
 }
 
 log_begin_msg()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "TEXT $@"
-	fi
-	_log_msg "Begin: $@ ..."
+	_log_msg "Begin: $@ ... "
 }
 
 log_end_msg()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "SUCCESS ok"
-	fi
-	_log_msg "Done."
+	_log_msg "done.\n"
 }
 
 # Add failure hook
@@ -62,6 +56,10 @@ try_failure_hooks()
 	fi
 	chvt 1
 
+	if [ -x /bin/plymouth ] && plymouth --ping; then
+		/bin/plymouth hide-splash > /dev/null 2>&1
+	fi
+
 	for hook in /tmp/mountroot-fail-hooks.d/*; do
 		if [ -x ${hook} ] && ${hook} mountfail; then
 			return 0
@@ -72,13 +70,15 @@ try_failure_hooks()
 
 panic()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "QUIT"
-	fi
-	chvt 1
+       if command -v chvt >/dev/null 2>&1; then
+               chvt 1
+       fi
+
+	echo "$@"
 
 	# Disallow console access
 	if [ -n "${panic}" ]; then
+		echo "Rebooting automatically due to panic= boot argument"
 		sleep ${panic}
 		reboot
 	fi
@@ -87,14 +87,13 @@ panic()
 	modprobe atkbd
 
 	run_scripts /scripts/panic
-
-	echo $@
-	PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
+	
+	REASON="$@" PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
 }
 
 maybe_break()
 {
-	if echo "${break}" | egrep -q "(,|^)$1(,|$)"; then
+	if echo "${break:-}" | egrep -q "(,|^)$1(,|$)"; then
 		panic "Spawning shell within the initramfs"
 	fi
 }
@@ -113,7 +112,7 @@ set_initlist()
 
 		# only allow variable name chars
 		case ${si_x#${initdir}/} in
-		*[![:alnum:]_]*)
+		*[![:alnum:]\._-]*)
 			[ "${verbose}" = "y" ] \
 			&& echo "$si_x ignored: not alphanumeric or '_' file"
 			continue
@@ -134,7 +133,14 @@ set_initlist()
 			continue
 		fi
 
-		initlist="${initlist} ${si_x#${initdir}/}"
+		# skip bad syntax
+		if ! sh -n ${si_x} ; then
+			[ "${verbose}" = "y" ] \
+			&& echo "$si_x ignored: bad syntax"
+			continue
+		fi
+		
+		initlist="${initlist:-} ${si_x#${initdir}/}"
 	done
 }
 
@@ -152,7 +158,8 @@ reduce_satisfied()
 				IFS="$OLD_IFS"
 				# only allow variable name chars
 				case ${rs_z} in
-				*[![:alnum:]_]*)
+				*[![:alnum:]\._-]*)
+
 						IFS="|"
 						continue
 						;;
@@ -167,23 +174,33 @@ reduce_satisfied()
 					IFS="|"
 					continue
 				fi
+				
+				# skip bad syntax
+				if ! sh -n ${initdir}/${rs_z}; then
+					IFS="|"
+				        continue
+				fi
+
 				tmpdeplist="${tmpdeplist} ${rs_z}"
 				break
 			done
 			IFS="$OLD_IFS"
 			;;
 		*)
+			# only allow variable name chars
 			case ${rs_y} in
-			*[![:alnum:]_]*)
+			*[![:alnum:]\._-]*)
 				continue
 				;;
 			esac
-			if [ ! -x ${initdir}/${rs_y} ]; then
-				continue
-			fi
-			if [ -d ${initdir}/${rs_y} ]; then
-				continue
-			fi
+			
+			# skip non executable scripts
+			[ ! -x ${initdir}/${rs_y} ] && continue
+			# skip directories
+			[ -d ${initdir}/${rs_y} ] && continue
+			# skip bad syntax
+			sh -n ${initdir}/${rs_y} || continue
+			
 			tmpdeplist="${tmpdeplist} ${rs_y}"
 			;;
 		esac
@@ -257,7 +274,7 @@ reduce_prereqs()
 get_prereq_pairs()
 {
 	set_initlist
-	for gp_x in ${initlist}; do
+	for gp_x in ${initlist:-}; do
 		echo ${gp_x} ${gp_x}
 		prereqs=$(${initdir}/${gp_x} prereqs)
 		for prereq in ${prereqs}; do
@@ -268,6 +285,7 @@ get_prereq_pairs()
 
 call_scripts()
 {
+	set -e
 	for cs_x in ${runlist}; do
 		[ -f ${initdir}/${cs_x} ] || continue
 		if [ x"$1" = "xoptional" ]; then
@@ -279,12 +297,24 @@ call_scripts()
 		if [ "${verbose}" = "y" ]; then
 			echo "Calling hook ${cs_x}"
 		fi
-		${initdir}/${cs_x}
-		# allow boot scripts to modify exported boot paramaters
-		if [ -e /conf/param.conf ]; then
+
+               ${initdir}/${cs_x} && ec=$? || ec=$?
+               # allow hooks to abort build:
+               # (except for iscan, due to a widely-deployed third-party
+               # package causing upgrade problems)
+               if [ "$ec" -ne 0 ] && [ "${cs_x}" != iscan ] && \
+                  [ "${cs_x}" != iscan-data ]; then
+                       echo "E: ${initdir}/${cs_x} failed with return $ec."
+                       # only errexit on mkinitramfs
+                       [ -n "${version}" ] && exit $ec
+               fi
+               # allow boot scripts to modify exported boot parameters
+
+	       if [ -e /conf/param.conf ]; then
 			. /conf/param.conf
-		fi
+	       fi
 	done
+	set +e
 }
 
 run_scripts()
@@ -294,29 +324,14 @@ run_scripts()
 
 	if [ -f ${initdir}/ORDER ]; then
 		. ${initdir}/ORDER
-	elif [ -x /usr/bin/tsort ]; then
+	elif command -v tsort >/dev/null 2>&1; then	
 		runlist=$(get_prereq_pairs | tsort)
-		call_scripts $2
+		call_scripts ${2:-}
 	else
 		get_prereqs
 		reduce_prereqs
 		call_scripts $2
 	fi
-}
-
-cache_run_scripts()
-{
-	DESTDIR=${1}
-	scriptdir=${2}
-	initdir=${DESTDIR}${scriptdir}
-	[ ! -d ${initdir} ] && return
-
-	runlist=$(get_prereq_pairs | tsort)
-	for crs_x in ${runlist}; do
-		[ -f ${initdir}/${crs_x} ] || continue
-		echo "${scriptdir}/${crs_x}" >> ${initdir}/ORDER
-		echo "[ -e /conf/param.conf ] && . /conf/param.conf" >> ${initdir}/ORDER
-	done
 }
 
 # Load custom modules first
@@ -347,74 +362,153 @@ parse_numeric() {
 	/*)
 		return
 		;;
-	*:*)
-		minor=${1#*:}
-		major=${1%:*}
-		;;
-	*)
+       [0-9]*:[0-9]*)
+               minor=$(echo ${1#*:} | sed -e 's/^0*//')
+               major=$(echo ${1%:*} | sed -e 's/^0*//')
+       ;;
+       [A-Fa-f0-9]*)
 		value=$(( 0x${1} ))
 		minor=$(( ${value} % 256 ))
 		major=$(( ${value} / 256 ))
 		;;
+       *)
+               return
+               ;;
 	esac
 
-	mknod -m 600 /dev/root b ${major} ${minor}
-	ROOT=/dev/root
+       if command -v udevd >/dev/null 2>&1; then
+               ROOT=/dev/block/${major}:${minor}
+       else
+               mknod -m 600 /dev/root b ${major} ${minor}
+               ROOT=/dev/root
+       fi
+}
+
+# Parameter: device node to check
+# Echos fstype to stdout
+# Return value: indicates if an fs could be recognized
+get_fstype ()
+{
+       local FS FSTYPE FSSIZE RET
+       FS="${1}"
+
+       # blkid has a more complete list of file systems,
+       # but fstype is more robust
+       eval $(fstype "${FS}" 2> /dev/null)
+       if [ "$FSTYPE" = "unknown" ] &&  command -v blkid >/dev/null 2>&1 ; then
+               FSTYPE=$(blkid -o value -s TYPE "${FS}")
+       elif [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
+               FSTYPE=$(/lib/udev/vol_id -t "${FS}" 2> /dev/null)
+       fi
+       RET=$?
+
+       if [ -z "${FSTYPE}" ]; then
+               FSTYPE="unknown"
+       fi
+
+       echo "${FSTYPE}"
+       return ${RET}
 }
 
 configure_networking()
 {
-	# networking already configured thus bail out
-	[ -n "${DEVICE}" ] && [ -e /tmp/net-"${DEVICE}".conf ] && return 0
+       if [ -n "${BOOTIF}" ]; then
+               # pxelinux sets BOOTIF to a value based on the mac address of the
+               # network card used to PXE boot, so use this value for DEVICE rather
+               # than a hard-coded device name from initramfs.conf. this facilitates
+               # network booting when machines may have multiple network cards.
+               # pxelinux sets BOOTIF to 01-$mac_address
 
-	if [ "${HWADDR}" ]; then
-		# select interface by MAC address
-		HWADDR="$(echo "${HWADDR}" | tr A-Z- a-z:)"
-		local iface
-		for iface in /sys/class/net/*; do
-			[ -f "$iface/address" ] || continue
-			if [ "$(cat "$iface/address")" = "${HWADDR}" ]; then
-				DEVICE="${iface#/sys/class/net/}"
+               # strip off the leading "01-", which isn't part of the mac
+               # address
+               temp_mac=${BOOTIF#*-}
+
+               # convert to typical mac address format by replacing "-" with ":"
+               bootif_mac=""
+               IFS='-'
+               for x in $temp_mac ; do
+                       if [ -z "$bootif_mac" ]; then
+                               bootif_mac="$x"
+                       else
+                               bootif_mac="$bootif_mac:$x"
+                       fi
+               done
+               unset IFS
+
+               # look for devices with matching mac address, and set DEVICE to
+               # appropriate value if match is found.
+               for device in /sys/class/net/* ; do
+                        if [ -f "$device/address" ]; then
+                               current_mac=$(cat "$device/address")
+                               if [ "$bootif_mac" = "$current_mac" ]; then
+                                       DEVICE=${device##*/}
+                                       break
+                               fi
+
 			fi
 		done
 	fi
+	
+	# networking already configured thus bail out
+	[ -n "${DEVICE}" ] && [ -e /tmp/net-"${DEVICE}".conf ] && return 0
 
 	# support ip options see linux sources
-	# Documentation/filesystems/nfsroot.txt
-	case ${IPOPTS} in
-	none|off)
-		# Do nothing
-		;;
-	""|on|any)
-		# Bring up device
-		ipconfig -t 60 ${DEVICE}
-		;;
-	dhcp|bootp|rarp|both)
-		ipconfig -t 60 -c ${IPOPTS} -d ${DEVICE}
-		;;
-	*)
-		ipconfig -t 60 -d $IPOPTS
+	# Documentation/filesystems/nfs/nfsroot.txt
+	# Documentation/frv/booting.txt
+       for ROUNDTTT in 2 3 4 6 9 16 25 36 64 100; do
 
-		# grab device entry from ip option
-		NEW_DEVICE=${IPOPTS#*:*:*:*:*:*}
-		if [ "${NEW_DEVICE}" != "${IPOPTS}" ]; then
-			NEW_DEVICE=${NEW_DEVICE%:*}
-		else
-			# wrong parse, possibly only a partial string
-			NEW_DEVICE=
-		fi
-		if [ -n "${NEW_DEVICE}" ]; then
-			DEVICE="${NEW_DEVICE}"
-		fi
-		;;
-	esac
+               # The NIC is to be configured if this file does not exist.
+               # Ip-Config tries to create this file and when it succeds
+               # creating the file, ipconfig is not run again.
+               for x in /tmp/net-"${DEVICE}".conf /tmp/net-*.conf ; do
+                       [ -e "$x" ] && break 2
+               done
+
+               case ${IP} in
+               none|off)
+                       # Do nothing
+                       ;;
+               ""|on|any)
+                       # Bring up device
+                       ipconfig -t ${ROUNDTTT} "${DEVICE}"
+                       ;;
+               dhcp|bootp|rarp|both)
+                       ipconfig -t ${ROUNDTTT} -c ${IP} -d "${DEVICE}"
+                       ;;
+               *)
+                       ipconfig -t ${ROUNDTTT} -d $IP
+
+                       # grab device entry from ip option
+                       NEW_DEVICE=${IP#*:*:*:*:*:*}
+                       if [ "${NEW_DEVICE}" != "${IP}" ]; then
+                               NEW_DEVICE=${NEW_DEVICE%:*}
+                       else
+                               # wrong parse, possibly only a partial string
+                               NEW_DEVICE=
+                       fi
+                       if [ -n "${NEW_DEVICE}" ]; then
+                               DEVICE="${NEW_DEVICE}"
+                       fi
+                       ;;
+               esac
+       done
 
 	# source ipconfig output
 	if [ -n "${DEVICE}" ]; then
 		# source specific bootdevice
 		. /tmp/net-${DEVICE}.conf
 	else
-		# source any interface as not exaclty specified
+		# source any interface...
+		# ipconfig should have quit after first response
 		. /tmp/net-*.conf
 	fi
 }
+
+
+# Wait for queued kernel/udev events
+wait_for_udev()
+{
+       command -v udevadm >/dev/null 2>&1 || return 0
+       udevadm settle ${1:+--timeout=$1}
+}
+
